### ISSUE TITLE
To do before first production

### ISSUE THREAD

**Issue by eelmoham** [itsOussamox/AkditalGPT-Chat#2]
To Do :
- Animated Navbar.
- Real suggestions.

To Fix :
- Responsiveness in the TopNav.
- GPT Prompt after clearing the chat.

**Comment by itsOussamox** [comment]
Done :
 - Responsiveness in the TopNav.
 - GPT Prompt after clearing the chat.

**Comment by itsOussamox** [comment]
Done : 
 - Animated Navbar (open/close)

**Comment by itsOussamox** [comment]
Done 👍🏽
